Milestone : To Do list: add & remove
jenadiusnicholaus/To-Do-list pull request #2
Opened 2022-03-31 07:22 UTC by jenadiusnicholaus

In this milestone:

1. Removed all hardcoded items from the tasks array.
2. Created a new JavaScript file for the new functionality called `todolistcrud.js.`
3. Implemented a function for adding a new task (add a new element to the array).
4. Implementing a function for deleting a task (remove an element from the array).
 `in progress`

2022-04-01 14:33 UTC, brytebee requested changes
Hi, @jenadiusnicholaus👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- No linter errors✔️
- proper documentation✔️
- great use of the filter method✔️
- proper storage of state in localStorage✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 14:33 UTC, brytebee commented on src/components/todolistcrud.js
> +    this.id = Date.now().toString(36) + Math.random().toString(36).substr(2);
- [ ] **Required:** Id should a number. It should be updatable.

![image](https://user-images.githubusercontent.com/27709832/161283458-01bc35dd-6d49-4ede-a8e5-bb32d6d70714.png)

2022-04-01 14:33 UTC, brytebee commented on src/style.css
> +  /* background-color: #c76161; */
- [ ] **Required:** Kindly remove all commented cod in your codebase. This is more professional and considered clean code.

2022-04-01 14:33 UTC, brytebee commented on src/components/todolistcrud.js
> +          // event.target.style.background='#c76161';
- [ ] **Required:** Kindly remove commented code.

2022-04-01 14:33 UTC, brytebee commented on src/components/todolistcrud.js
> +/* eslint-disable max-classes-per-file */
- [ ] **Optional:** Rather than disable the linter strive to fix them as this makes you more accustomed to the style guide of the tech.

2022-04-01 15:46 UTC, medaminedev66 requested changes
Hi @jenadiusnicholaus, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- New tasks have the property `completed` set to `false` and the property `index` set to the value of the new array length

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 15:46 UTC, medaminedev66 commented on src/components/todolistcrud.js
> +    };
- [ ] Following the project requirements, Deleting a task should update all remaining tasks' Ids, so they represent the current list order and are **unique**. As you see on the screenshot, I deleted `task 2`, I added `task 5` and I noticed that `task 5` and `task 4` have the same id. Kindly work on that.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/77190203/161296534-329de7b0-de1a-4b30-8006-102b6fb71986.png">

2022-04-01 15:46 UTC, medaminedev66 commented on webpack.config.js
> +    // hot: true,
- [ ] Kindly remove the commented code to make your code clean.

2022-04-01 15:46 UTC, medaminedev66 commented on src/style.css
> +  /* background-color: #c76161; */
- [ ] The same thing here, Kindly remove the commented code.

2022-04-01 15:49 UTC, medaminedev66 commented on src/components/todolistcrud.js
> +/* eslint-disable max-classes-per-file */
- [ ] As requested by the previous reviewer, Kindly don't disable the linter.

2022-04-02 10:14 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @jenadiusnicholaus, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please use this time to learn more about how to update `id` in the localStorage we have for example we have 3 tasks of ids [1,2,3] we delete number to we should be left with [1,2] instead of [1,3] 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-02 10:19 UTC, merged